feat: make list public by default
raffomania/linkblocks pull request #52
Opened 2024-04-28 16:19 UTC by kimlimjustin

Adding features mentioned in #44. I've made the lists part to be public by default after initial creation, making non-authenticated users able to see it just by opening the same link as what the authenticated users use to view their lists.

In order make this possible, I've created a new struct called `Authenticated` which does not force-checking every request and send them to the login page if not authenticated, instead it just simply says that "this is not authenticated" if it does not authenticated while returning the `auth_user` properties if authenticated. 

Then, I added a new column to the `lists`, called `prvate` (not `private` or `priv` as they are keywords so yeah I chose some random key), which is set to false as default. Finally, it uses conditional rendering according to the key. I've also added a button so that users are able to toggle the publicity of the list.

2024-04-30 13:33 UTC, raffomania requested changes
Thanks for taking the time to implement this! I think there are some opportunities to streamline the code we need to get this feature.

A thing that would be really nice would be a checkbox in the `CreateList` form allowing users to choose between private and public lists when creating them. That's optional though, I'll merge this PR without that feature.

2024-04-30 13:33 UTC, raffomania commented on src/routes/lists.rs
> +    if list.prvate {
You can replace this whole block with:

```rs
db::lists::set_private(&mut tx, query.list_id, list.private).await?;
```

2024-04-30 13:33 UTC, raffomania commented on templates/list.html
> +    <a
After clicking this link, the whole section is empty. You'll need to add `id="toggle_publicity"`, remove the `hx-target` attribute and add `hx-swap="outerHTML"` to make it work.

2024-06-04 10:01 UTC, kimlimjustin commented
Hello @raffomania, I've made some updates for this PR, could you please take a look again? Thanks in advance

2024-09-23 12:12 UTC, raffomania approved these changes

2024-09-23 12:12 UTC, merged